# Generated by Django 3.2.4 on 2021-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20210727_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/test.wav'),
        ),
    ]
