# Generated by Django 3.2.4 on 2021-07-28 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_audio_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
